name: CyberChef
on: 
  schedule:
    - cron: '*/30 * * * *' # Runs every first and 30th minute

jobs:

  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the repo directory
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: CyberChef
      env:
        TZ: Asia/Shanghai
      run: |
        env SECRETS_PUSH_URL=${{ secrets.PUSH_URL}}\
            SECRETS_GITEE_USERNAME=${{ secrets.GITEE_USERNAME}}\
            SECRETS_GITEE_CLIENT_ID=${{ secrets.GITEE_CLIENT_ID}}\
            SECRETS_GITEE_CLIENT_SECRET=${{ secrets.GITEE_CLIENT_SECRET}}\
            SECRETS_GITEE_PASSWORD=${{ secrets.GITEE_PASSWORD}}\
            bash cyberchef.sh


        

